kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-get-everything
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-read-all-access
subjects:
- apiGroup: ""
  kind: User
  name: Dev
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: dev-get-everything