apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
  namespace: test
  labels:
    app: test-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30081
  selector:
    app: test-nginx