apiVersion: v1
kind: Service
metadata:
  name: prod-nginx-svc
  namespace: production
  labels:
    app: prod-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: prod-nginx