apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        environment: {{ .Values.environment }}
    spec:
      volumes:
        - name: {{ .Values.container.name }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Values.container.name }}-pv-claim
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - mountPath: "/var/lib/clamav"
              name: {{ .Values.container.name }}-pv-storage
