apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.container.name }}-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi