apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.container.name }}
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: {{ .Values.service.nodeport}}
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
